# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Optional

from pydantic import Field as FieldInfo

from ..._models import BaseModel

__all__ = [
    "ObjectGetPresignedURLResponse",
    "Result",
    "ResultData",
    "ResultDataObjectList",
    "ResultDataObjectListObjectSignedInfo",
]


class ResultDataObjectListObjectSignedInfo(BaseModel):
    fields: Optional[Dict[str, str]] = None
    """
    Form fields required for S3 POST upload (key, policy, x-amz-\\** headers,
    Content-Type)
    """

    max_size: Optional[int] = FieldInfo(alias="maxSize", default=None)
    """Maximum file size in bytes. image: 10MB, file: 100MB, video: 500MB"""

    url: Optional[str] = None
    """Pre-signed S3 upload URL"""


class ResultDataObjectList(BaseModel):
    """Signed object item.

    MMS echoes back the request fields alongside generated signing info.
    """

    file_id: Optional[str] = FieldInfo(alias="fileId", default=None)
    """Echoed file ID from request"""

    file_name: Optional[str] = FieldInfo(alias="fileName", default=None)
    """Echoed file name from request"""

    file_type: Optional[str] = FieldInfo(alias="fileType", default=None)
    """Echoed file type from request"""

    object_key: Optional[str] = FieldInfo(alias="objectKey", default=None)
    """S3 object key (generated by MMS)"""

    object_signed_info: Optional[ResultDataObjectListObjectSignedInfo] = FieldInfo(
        alias="objectSignedInfo", default=None
    )


class ResultData(BaseModel):
    """On success: contains objectList. On validation error: string error message."""

    object_list: Optional[List[ResultDataObjectList]] = FieldInfo(alias="objectList", default=None)


class Result(BaseModel):
    data: Optional[ResultData] = None
    """On success: contains objectList. On validation error: string error message."""


class ObjectGetPresignedURLResponse(BaseModel):
    """
    MMS service response format (Gateway transparent proxy, not standard ErrorResponse format)
    """

    error: Optional[str] = None
    """Error message. 'OK' on success, error description on failure"""

    request_id: Optional[str] = None
    """MMS request tracking ID"""

    result: Optional[Result] = None

    status: Optional[int] = None
    """MMS status code. 0 = success, 2018 = validation error"""
