# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional

from pydantic import Field as FieldInfo

from ..._models import BaseModel
from .object_signed_info import ObjectSignedInfo

__all__ = ["ObjectSignItem"]


class ObjectSignItem(BaseModel):
    """Signed object item.

    MMS echoes back the request fields alongside generated signing info.
    """

    file_id: Optional[str] = FieldInfo(alias="fileId", default=None)
    """Echoed file ID from request"""

    file_name: Optional[str] = FieldInfo(alias="fileName", default=None)
    """Echoed file name from request"""

    file_type: Optional[str] = FieldInfo(alias="fileType", default=None)
    """Echoed file type from request"""

    object_key: Optional[str] = FieldInfo(alias="objectKey", default=None)
    """S3 object key (generated by MMS)"""

    object_signed_info: Optional[ObjectSignedInfo] = FieldInfo(alias="objectSignedInfo", default=None)
